name: Windows Signer
on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      files:
        required: true
        type: string
jobs:
  sign:
    runs-on: [self-hosted, win-signer]
    env:
      ARCHIVE_DIR: ${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.artifact-name }}
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ env.ARCHIVE_DIR }}
      - name: sign packaged files
        shell: cmd
        run: |
          cd ${{ env.ARCHIVE_DIR }}/out
          signtool sign /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /a ${{ inputs.files }}
      - name: make installers
        shell: cmd
        run: |
          cd ${{ env.ARCHIVE_DIR }}
          node make-squirrel.cjs
          node make-nsis.cjs
      - name: sign installers
        shell: cmd
        run: |
          cd ${{ env.ARCHIVE_DIR }}
          @echo off & setlocal enabledelayedexpansion & set "buildType=%BUILD_TYPE%" & set "signtoolCommand=signtool sign /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /a" & for /r .\out\%buildType%\make %%f in (*.exe *.msi) do ( set "filePath=%%~f" & set "relativePath=!filePath:.\out\=!" & set "signtoolCommand=!signtoolCommand! "!relativePath!"") & call !signtoolCommand!
      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: signed-${{ inputs.artifact-name }}
          path: ${{ env.ARCHIVE_DIR }}/out/${{ env.BUILD_TYPE }}/make
